#!/bin/sh
set -eu

ROOT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
DIST_DIR="${DIST_DIR:-$ROOT_DIR/dist}"
VERSION="${KISS_VERSION:-$(git -C "$ROOT_DIR" describe --tags --always --dirty 2>/dev/null || echo dev)}"
REPO="${KISS_REPO:-wwulfric/kiss}"
FORMULA_PATH="${FORMULA_PATH:-$DIST_DIR/kiss.rb}"

if [ ! -f "$DIST_DIR/checksums.txt" ]; then
  echo "missing checksums: $DIST_DIR/checksums.txt" >&2
  exit 1
fi

formula_version=${VERSION#v}

checksum_for() {
  artifact="$1"
  checksum=$(awk -v artifact="$artifact" '$2 == artifact { print $1 }' "$DIST_DIR/checksums.txt")
  if [ -z "$checksum" ]; then
    echo "missing checksum for $artifact" >&2
    exit 1
  fi
  printf '%s' "$checksum"
}

url_for() {
  artifact="$1"
  printf 'https://github.com/%s/releases/download/%s/%s' "$REPO" "$VERSION" "$artifact"
}

darwin_amd64="kiss_${VERSION}_darwin_amd64.tar.gz"
darwin_arm64="kiss_${VERSION}_darwin_arm64.tar.gz"
linux_amd64="kiss_${VERSION}_linux_amd64.tar.gz"
linux_arm64="kiss_${VERSION}_linux_arm64.tar.gz"

darwin_amd64_sha=$(checksum_for "$darwin_amd64")
darwin_arm64_sha=$(checksum_for "$darwin_arm64")
linux_amd64_sha=$(checksum_for "$linux_amd64")
linux_arm64_sha=$(checksum_for "$linux_arm64")

mkdir -p "$(dirname -- "$FORMULA_PATH")"

cat > "$FORMULA_PATH" <<EOF
# This file is generated by scripts/generate-homebrew-formula.sh.
class Kiss < Formula
  desc "Explicit skill store and launcher for coding agents"
  homepage "https://github.com/$REPO"
  version "$formula_version"

  on_macos do
    if Hardware::CPU.arm?
      url "$(url_for "$darwin_arm64")"
      sha256 "$darwin_arm64_sha"
    else
      url "$(url_for "$darwin_amd64")"
      sha256 "$darwin_amd64_sha"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "$(url_for "$linux_arm64")"
      sha256 "$linux_arm64_sha"
    else
      url "$(url_for "$linux_amd64")"
      sha256 "$linux_amd64_sha"
    end
  end

  def install
    bin.install "kiss"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/kiss --version")
  end
end
EOF

echo "Generated Homebrew formula at $FORMULA_PATH"
